# Generated by Django 4.2.16 on 2024-09-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('information', models.TextField(blank=True, null=True, verbose_name='содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='фото блога')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='состояние публикации')),
                ('count_views', models.IntegerField(default=0, verbose_name='количетсво просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блогов',
            },
        ),
    ]
