# Generated by Django 5.1 on 2024-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(verbose_name='дата последнего изменения'),
        ),
    ]
