# Generated by Django 4.2 on 2024-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-category_product', '-product_name'), 'permissions': [('set_info_product', 'Can info product'), ('set_category_product', 'Can info product'), ('set_published_status', 'Can published product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='статус публикации продукта'),
        ),
    ]
